name: SaltStack GitOps Continuous Deployment

# Pipeline tự động kích hoạt mỗi khi có hành động PUSH vào nhánh main
on:
  push:
    branches:
      - main

jobs:
  deploy-infrastructure:
    name: Sync and Apply Infrastructure State
    # Chỉ định chạy trên chính con máy ảo Salt Master của bạn
    runs-on: Salt

    steps:

      - name: Check current user
        run: whoami
      # Bước 1: Ra lệnh cho Salt Master xóa cache cũ, kéo code mới nhất từ GitHub Repo về RAM
      - name: 🔄 Update Salt Fileserver Cache from Git
        run: |
          sudo salt-run fileserver.update
          
      # Bước 2: Ra lệnh cho toàn bộ các Minion cập nhật lại bộ nhớ đệm dữ liệu Pillar
      - name: 🔋 Refresh Minions Pillar Cache
        run: |
          sudo salt '*' saltutil.refresh_pillar

      # Bước 3: Thực thi áp đặt trạng thái để cập nhật Nginx (Continuous Deployment)
      - name: 🚀 Continuous Deployment - Apply Nginx State
        run: |
          sudo salt '*' state.apply nginx
